title:               Workingmen's Benevolent Association
tagline:             'Miners Union'
description:         'A 19th-century <a href="https://en.wikipedia.org/wiki/Workingmen%27s_Benevolent_Association_of_Schuylkill_County">labor organization</a> that consisted mainly of coal miners.'
url:                 https://www.eve-wba.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bubba Dumptruck
  url:               https://zkillboard.com/character/2118545592/
  email:             yomomma@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-JSN7EPY1XM
